---
development_packages:
  # java
  - java-1.8.0-openjdk-devel
  - java-1.8.0-openjdk-src
  - java-11-openjdk-devel
  - java-11-openjdk-src
  - java-latest-openjdk-devel
  - java-latest-openjdk-src

  # python
  - python3-virtualenvwrapper
  - poetry

  # nodejs
  - nodejs

  # misc
  - jq
  - asciidoctor

development_flatpaks:
  - com.visualstudio.code-oss

development_snaps:
  - yq
  - insomnia

development_sysctl:
  - key: fs.inotify.max_user_watches
    value: 524288
