---
tuned_active_builtin_profile: "{{ tuned_profiles[ansible_form_factor] }}"

laptop_packages:
  - thermald
  - tlp
  - tlp-rdw

thinkpad_packages:
  - kernel-devel
  - akmod-acpi_call
  - akmod-tp_smapi

tlp_linrunner_repo_url: http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ ansible_distribution_major_version }}.noarch.rpm
guake_unbind: activate-window-menu
keybindings_key: org.gnome.desktop.wm.keybindings
