---
- include_role:
    name: stocky37.core.guake

- include_role:
    name: giovtorres.tuned
    apply:
      become: yes

- include_role:
    name: jaredhocutt.google_chrome

- include_role:
    name: stocky37.core.1password
